name: update-mesa-arm64-nightly

on:
  schedule:
     - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update-mesa-nightly:
    runs-on: ubuntu-24.10
    container: ubuntu:24.10
    defaults:
      run:
        shell: bash

    steps:
      - name: Install dependencies
        run: |
          # add dependencies expected by scripts
          export DEBIAN_FRONTEND=noninteractive
          echo "deb [arch=amd64,i386] http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ oracular main restricted universe multiverse
          deb-src [arch=amd64,i386] http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ oracular main restricted universe multiverse
          deb [arch=amd64,i386] http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ oracular-updates main restricted universe multiverse
          deb-src [arch=amd64,i386] http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ oracular-updates main restricted universe multiverse
          deb [arch=amd64,i386] http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ oracular-backports main restricted universe multiverse
          deb-src [arch=amd64,i386] http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ oracular-backports main restricted universe multiverse
          deb [arch=arm64,armhf] http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ oracular main restricted universe multiverse
          deb-src [arch=arm64,armhf] http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ oracular main restricted universe multiverse
          deb [arch=arm64,armhf] http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ oracular-updates main restricted universe multiverse
          deb-src [arch=arm64,armhf] http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ oracular-updates main restricted universe multiverse
          deb [arch=arm64,armhf] http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ oracular-backports main restricted universe multiverse
          deb-src [arch=arm64,armhf] http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ oracular-backports main restricted universe multiverse" > /etc/apt/sources.list
          apt update
          dpkg --add-architecture arm64
          apt full-upgrade -y
          apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu meson cmake sudo git llvm-19 llvm-19-dev clang-19 libclang-19-dev libpolly-19-dev curl -y
          
      - name: Build mesa
        run: |
          cd /opt/
          git clone --depth 1 https://gitlab.freedesktop.org/mesa/mesa.git mesa-sources
          git clone https://github.com/MastaG/mesa-turnip-ppa.git
          cp mesa-turnip-ppa/turnip-patches/* mesa-sources/
          cd mesa-sources
          patch -p1 < dri3.patch
          patch -p1 < fix-for-anon-file.patch
          patch -p1 < fix-for-getprogname.patch
          mkdir b
          cd b
          echo "meson .. --cross-file=cross_arm64.txt --libdir=lib/aarch64-linux-gnu -Dgallium-drivers=freedreno,virgl,zink,d3d12,softpipe,llvmpipe,svga -Dvulkan-drivers=freedreno,swrast,virtio -Dglx=dri -Dplatforms=x11,wayland -Dbuildtype=release -Dllvm=enabled -Dxlib-lease=enabled -Dgles2=enabled -Dgles1=enabled -Dgallium-nine=true -Dgallium-opencl=icd -Degl-native-platform=x11 -Degl=enabled -Dfreedreno-kmds=kgsl,msm,virtio,wsl  -Dvulkan-beta=true -Dglx-direct=true -Dtools=drm-shim,freedreno,etnaviv,glsl,nir -Dgallium-vdpau=enabled -Dopengl=true -Dosmesa=true -Dpower8=enabled -Dglvnd=enabled -Dteflon=true -Dvideo-codecs=all -Dgallium-d3d12-video=enabled -Dgallium-d3d12-graphics=enabled -Dxmlconfig=enabled -Dgbm=enabled -Dshader-cache=enabled -Dgallium-va=enabled -Dgallium-xa=enabled -Dgallium-rusticl=true -Dgallium-rusticl-enable-drivers=auto -Dshader-cache-max-size='1G' -Dmicrosoft-clc=enabled -Dspirv-to-dxil=true -Ddraw-use-llvm=true -Dllvm-orcjit=true -Dsse2=true -Ddatasources=freedreno --prefix=/opt/mesa/" | sudo tee -a /opt/mesa-sources/b/build.sh
          echo "[binaries]
          c = 'aarch64-linux-gnu-gcc'
          cpp = 'aarch64-linux-gnu-g++'
          ar = 'aarch64-linux-gnu-ar'
          strip = 'aarch64-linux-gnu-strip'
          pkgconfig = 'pkg-config'
          [host_machine]
          system = 'linux'
          cpu_family = 'aarch64'
          cpu = 'aarch64'
          endian = 'little'" | sudo tee -a /opt/mesa-sources/b/cross_arm64.txt
          chmod +x build.sh
          ./build.sh
          cd /opt/
          tar -cjvf mesa-nightly-arm64.tar.gz mesa

      - uses: actions/upload-artifact@v3
        with:
          name: mesa-nightly-arm64
          path: /opt/mesa-nightly-arm64.tar.gz
