name: update-box64-nightly

on:
  schedule:
     - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update-box64:
    runs-on: ubuntu-22.04
    container: ubuntu:22.04
    defaults:
      run:
        shell: bash

    steps:
      - name: Install dependencies
        run: |
          # add dependencies expected by scripts
          export DEBIAN_FRONTEND=noninteractive
          sed -i "s/jammy/noble/g" /etc/apt/sources.list
          apt update
          #apt upgrade -y
          apt install -y software-properties-common lsb-release \
          sudo wget curl build-essential jq autoconf automake \
          pkg-config ca-certificates rpm apt-utils \
          python3 make gettext pinentry-tty devscripts dpkg-dev 
          sudo apt install -y gcc-14-aarch64-linux-gnu g++-14-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu
          #pkg-config-aarch64-linux-gnu          
          sudo sed -i "s/^deb/deb [arch=amd64,i386]/g" /etc/apt/sources.list
          # echo "deb [arch=arm64,armhf] http://ports.ubuntu.com/ $(lsb_release -s -c) main universe multiverse restricted" | sudo tee -a /etc/apt/sources.list
          # echo "deb [arch=arm64,armhf] http://ports.ubuntu.com/ $(lsb_release -s -c)-updates main universe multiverse restricted" | sudo tee -a /etc/apt/sources.list
          echo "deb [arch=arm64,armhf] http://ports.ubuntu.com/ noble main universe multiverse restricted" | sudo tee -a /etc/apt/sources.list
          echo "deb [arch=arm64,armhf] http://ports.ubuntu.com/ noble-updates main universe multiverse restricted" | sudo tee -a /etc/apt/sources.list
          sudo dpkg --add-architecture arm64
          sudo apt update
          sudo apt install -y libc6:arm64
          # install new enough git to run actions/checkout
          sudo add-apt-repository ppa:git-core/ppa -y
          sudo apt update
          sudo apt install -y git cmake
          # avoid "fatal: detected dubious ownership in repository" error
          git config --global --add safe.directory '*'

      - name: Build debs
        run: |
          cd /opt/
          rm -rf box64
          #git clone https://github.com/ptitSeb/box64
          #正式版
          wget 'https://github.com/ptitSeb/box64/archive/refs/tags/v0.3.6.tar.gz'
          tar -xvf v0.3.6.tar.gz
          mv v0.3.6 box64
          cd box64
          mkdir build
          cd build
          echo '# toolchain-aarch64.cmake
          set(CMAKE_SYSTEM_NAME Linux)
          set(CMAKE_SYSTEM_PROCESSOR aarch64)
          set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
          set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)
          set(CMAKE_ASM_COMPILER aarch64-linux-gnu-gcc)' | sudo tee /opt/box64/build/toolchain-aarch64.cmake > /dev/null
          echo 'cmake .. -DCMAKE_TOOLCHAIN_FILE=toolchain-aarch64.cmake -DARM64=ON -DSD8G2=ON -DBAD_SIGNAL=ON -DBOX32=ON -DBOX32_BINFMT=ON -DARM_DYNAREC=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo' | sudo tee /opt/box64/build/build.sh > /dev/null
          chmod +x build.sh
          ./build.sh
          make -j$(nproc)
          cpack -G DEB

      - uses: actions/upload-artifact@v3
        with:
          name: box64-SD8G2
          path: /opt/box64/build/*.deb
